language: lilypond
dist: focal
script: make
before_script: lilypond --version
addons:
  apt:
    packages:
    - lilypond
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
