language: lilypond
os: linux
dist: focal
addons:
  apt:
    packages:
    - lilypond
before_script:
  - lilypond --version
  - for FILE in *.ly; do sed -i -e "s/tagline = \"\"/tagline = \"git revision $(git log -n 1 --pretty=format:%h -- $FILE)\"/g;" "$FILE"; done
script: make mid pdf -j 2
before_deploy:
  - mv *.{pdf,mid,midi} pages/
  - cd pages/
  - ./rebuild_index.sh
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: pages
  on:
    branch: master
