language: lilypond
os: linux
dist: focal
addons:
  apt:
    packages:
    - lilypond
before_script:
  - lilypond --version
  - for FILE in *.ly; do sed -i -e "s/tagline = \(\"\"\|##f\)/tagline = \"git revision $(git log -n 1 --pretty=format:%h -- $FILE)\"/g;" "$FILE"; done
script: make pdf mid LPFLAGS="-djob-count=2 -dcheck-internal-types -dwarning-as-error" -j 2
before_deploy:
  - mv *.+(pdf|mid|midi) gh-pages/
  - cd gh-pages/
  - ./rebuild_index.sh
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: gh-pages
  on:
    branch: master
