language: lilypond
os: linux
dist: focal
script: make -j 2
before_script: lilypond --version
addons:
  apt:
    packages:
    - lilypond
before_deploy:
  - mv *.{pdf,mid,midi} pages/
  - cd pages/
  - ./rebuild_index.sh
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: pages
  on:
    branch: master
